# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-08 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plc_data_one',
            fields=[
                ('deviceName', models.CharField(default=None, max_length=20, unique=True)),
                ('currentDate', models.DateTimeField(default=0, primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('do', models.FloatField()),
                ('pH', models.FloatField()),
                ('stir', models.FloatField()),
                ('feed', models.FloatField()),
                ('acid', models.FloatField()),
                ('base', models.FloatField()),
                ('ca', models.FloatField()),
                ('o2', models.FloatField()),
                ('n2', models.FloatField()),
                ('co2', models.FloatField()),
            ],
            options={
                'db_table': 'Plc_data_one',
            },
        ),
        migrations.CreateModel(
            name='Plc_data_one_settings',
            fields=[
                ('deviceName', models.CharField(default=None, max_length=20, unique=True)),
                ('currentDate', models.DateTimeField(default=0, primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('do', models.FloatField()),
                ('pH', models.FloatField()),
                ('stir', models.FloatField()),
                ('feed', models.FloatField()),
                ('acid', models.FloatField()),
                ('tempSwitch', models.CharField(max_length=1)),
                ('doSwitch', models.CharField(max_length=1)),
                ('phSwitch', models.CharField(max_length=1)),
                ('stirSwitch', models.CharField(max_length=1)),
                ('feedSwitch', models.CharField(max_length=1)),
                ('acidSwitch', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Plc_data_one_settings',
            },
        ),
        migrations.CreateModel(
            name='PlcTestSettingTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default=None, max_length=20, unique=True)),
                ('currentDate', models.DateTimeField(default=0)),
                ('temp', models.FloatField()),
                ('pH', models.FloatField()),
                ('stir', models.FloatField()),
            ],
            options={
                'db_table': 'TestSetting',
            },
        ),
    ]
